### ISSUE TITLE
Start Button is Clickable but no Attached Function

### ISSUE THREAD

**Issue by aonanam** [CIDARLAB/Neptune-iGEM-2016#35]
![image](https://cloud.githubusercontent.com/assets/6097214/18678025/bbf35cdc-7f28-11e6-865a-206583f2c3ba.png)
The blue checkmark button changes the mouse and color as if it is a clickable button, but nothing happens on clicking.

Possible fixes: 
-Make the button not change its color and mouse on mouseover
-Move the Start description out of the timeline graphic, possible as a summary paragraph above the graphic

**Comment by anishasthana** [comment]
Any ideas on what we would prefer? @rkrishnasanka

**Comment by anishasthana** [comment]
For the time being, I changed the button to not change colour + mouse.
