### ISSUE TITLE
unable to see new project button when you specify a directory with a lot of files

### ISSUE THREAD

**Issue by johanos** [CIDARLAB/Neptune-iGEM-2016#36]
sometimes you can zoom out, but it wont help if you have so many.

recommended fix: wrap those results in a scroll view

**Comment by anishasthana** [comment]
<img width="1078" alt="new project button missing" src="https://cloud.githubusercontent.com/assets/6526150/20360700/bf5d9ee4-ac02-11e6-8651-5f32e51d7960.PNG">

Here's a screenshot of the bug in question.

**Comment by rkrishnasanka** [comment]
@anishasthana if you want to fix this then just assign it to yourself so that others will keep away from this.

**Comment by anishasthana** [comment]
I was trying to figure out how to assign it, actually.
