### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by jsreid13** [CIDARLAB/Neptune-iGEM-2016#54]
I acknowledge that this project hasn't been worked on for over a year now so it was kind of a long shot that it would still build. However it looks like it is close to still being about to properly install, most of the dependencies are deprecated but still useable, however the installation fails with the package node-serialport. It seems the package has changed names and can't be found (from "serialport-v3.1.2-node-v64-linux-x64.tar.gz" to "serialport-v3.1.2-node-v48-linux-x64.tar.gz").

**Comment by jsreid13** [comment]
I removed serialport from the package.json file and now the installation works when building from source. However, running start-neptune after linking threw another error with serialcommunication.js but after commenting out all references to serialport from that file it now runs properly on port 3000.

**Comment by rkrishnasanka** [comment]
Sure let us know how you plan to use the inputs and outputs. We have updated a lot of internals that are used in this.
